#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server
# Configures HAProxy to distribute traffic to web-01 and web-02 servers using roundrobin algorithm
# Ensures HAProxy can be managed via an init script

# Update package list
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAProxy
server_config="
frontend myrobert.tech-frontend
    bind *:80
    mode http
    default_backend myrobert.tech-backend

backend myrobert.tech-backend
    balance roundrobin
    server 45099-web-01 54.173.104.114:80 check
    server 45099-web-02 54.172.150.81:80 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to start with system boot
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart

