#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  myrobert.tech-frontend
        bind *:80
        mode http
        default_backend myrobert.tech-backend
backend myrobert.tech-backend
        balance roundrobin
        server 45099-web-01 54.173.104.114:80 check
        server 45099-web-02 54.172.150.81:80 check
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  myrobert.tech-frontend
          bind *:80
          mode http
          default_backend myrobert.tech-backend
backend   myrobert.tech-backend
          balance roundrobin
          server 45099-web-01 54.173.104.114:80 check
          server 45099-web-02 54.172.150.81:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart54.172.150.81:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
