#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private
# key ~/.ssh/school with the user ubuntu
ssh ubuntu@54.173.104.114 -i ~/.ssh/school
ssh ubuntu@54.227.201.47
